# ========================
# Journal whitelist
# ========================
JOURNALS = [
    "Cell",
    "Nature",
    "Science",
    "Cancer Cell",
    "Nature Biotechnology",
    "Nature Methods",
    "Immunity",
    "Nature Immunology",
    "Science Advances",
    "Science Immunology",
    "Science Translational Medicine",
    "Nature Cancer",
    "Nature Genetics",
    "Nature Medicine",
    "Nature Biomedical Engineering",
    "Cell Systems",
    "Cell Reports Methods",
    "PNAS",
    "Nature Chemical Biology",
    "Nature Communications",
    "eLife",
]
# Journals that publish many non-research items (news, editorials, corrections).
# For these, Crossref queries add has-abstract:true to filter to research articles only.
FILTER_ABSTRACT_JOURNALS = {"Nature", "Science", "PNAS"}

INCLUDE_BIORXIV_DEFAULT = True
INCLUDE_MEDRXIV_DEFAULT = False

JOURNAL_ISSN = {
    "Cell": ['0092-8674', '1097-4172'],
    "Nature": ['0028-0836', '1476-4687'],
    "Science": ['0036-8075', '1095-9203'],
    "Cancer Cell": ['1535-6108', '1878-3686'],
    "Nature Biotechnology": ['1087-0156', '1546-1696'],
    "Nature Methods": ['1548-7091', '1548-7105'],
    "Immunity": ['1074-7613', '1097-4180'],
    "Nature Immunology": ['1529-2908', '1529-2916'],
    "Science Advances": ['2375-2548'],
    "Science Immunology": ['2470-9468'],
    "Science Translational Medicine": ['1946-6234'],
    "Nature Cancer": ['2662-1347'],
    "Nature Genetics": ['1061-4036', '1546-1718'],
    "Nature Medicine": ['1078-8956', '1546-170X'],
    "Nature Biomedical Engineering": ['2157-846X'],
    "Cell Systems": ['2405-4712'],
    "Cell Reports Methods": ['2667-2375'],
    "PNAS": ['0027-8424', '1091-6490'],
    "Nature Chemical Biology": ['1552-4450', '1552-4469'],
    "Nature Communications": ['2041-1723'],
    "eLife": ['2050-084X'],
}

# Must-read list size
MUST_READ_N = 20

# Cap how many papers from the same journal can appear in each Must-read list
MAX_PER_JOURNAL_MUST_READ = 3

# Tech vs Bio tag buckets (match keys in CORE_KEYWORDS)
TECH_KEYS = ["proximity", "sequencing", "spatial", "proteomics", "spatial_interactome", "ai_ml"]
BIO_KEYS  = ["lymph_node", "germinal_center", "immune", "cancer", "drug", "tls", "bcell_antibody"]


# ========================
# Focus: B cell antibody screening / discovery
# ========================
FOCUS_BCELL_ANTIBODY_KEYS = [
    # --- Core task: antibody discovery / screening ---
    "antibody screening",
    "antibody discovery",
    "single-cell antibody",
    "single cell antibody",
    "monoclonal antibody discovery",
    "neutralizing antibody",

    # --- Antigen specificity & BCR ---
    "antigen-specific b cell",
    "antigen specific b cell",
    "b cell receptor",
    "bcr",
    "bcr sequencing",
    "vdj sequencing",
    "vdj",
    "paired heavy and light chain",
    "heavy and light chain pairing",
    "vh vl",
    "vh/vl",

    # --- Secretion capture / functional readout ---
    "antibody secretion",
    "secreted antibody",
    "secretion capture",
    "antibody capture",
    "affinity capture",
    "immune complex capture",

    # --- Surface-tethered antigen / display concepts ---
    "tethered antigen",
    "cell-surface tether",
    "cell surface tether",
    "surface-tethered",
    "surface tethered",
    "membrane-tethered antigen",
    "membrane tethered antigen",
    "cell-surface display",
    "cell surface display",
    "antigen display",

    # --- Readout via oligo / sequencing ---
    "oligo-tagged antibody",
    "oligo tagged antibody",
    "dna-barcoded antibody",
    "dna barcoded antibody",
    "antibody-oligo conjugate",
    "antibody oligo conjugate",
    "dna-conjugated antibody",
    "dna conjugated antibody",
    "antibody-derived tag",
    "antibody derived tag",
    "adt",
    "cite-seq",
    "cite seq",
    "feature barcode",

    # --- Screening platforms (optional but useful) ---
    "single-cell screening",
    "single cell screening",
    "microfluidic",
    "droplet",
    "nanowell",
]

# ========================
# Core keyword lexicon
# ========================
CORE_KEYWORDS = {
    # --- Technology ---
    "proximity": [
        "proximity",
        "proximal",
        "proximity ligation",
        "proximity ligation assay",
        "pla",
        "proximity sequencing",
        "prox-seq",
        "protein interaction",
        "protein-protein interaction",
        "ppi",
        "interactome",
        "protein interactome",
        "complexome",
        "signaling complex",
        "receptor complex",
    ],
    "sequencing": [
        "sequencing",
        "single-cell",
        "single cell",
        "scrna",
        "rna-seq",
        "atac-seq",
        "multiome",
        "cite-seq",
        "perturb-seq",
        "crispr screen",
        "guide rna",
    ],
    "spatial": [
        "spatial",
        "spatial transcriptomics",
        "spatial proteomics",
        "visium",
        "visium hd",
        "slide-seq",
        "slideseq",
        "stereoseq",
        "seq-scope",
        "merfish",
        "seqfish",
        "cosmx",
        "xenium",
        "codex",
        "imc",
        "imaging mass cytometry",
    ],
    "proteomics": [
        "proteomics",
        "mass spectrometry",
        "mass-spec",
        "lc-ms",
        "lc-ms/ms",
        "ms-based",
        "phosphoproteomics",
        "protein profiling",
        "olink",
        "somalogic",
        "cytof",
    ],

    "spatial_interactome": [
        "spatial interactome",
        "spatial interactomics",
        "spatial protein interaction",
        "spatial protein-protein interaction",
        "spatial ppi",
        "in situ interactome",
        "in situ protein interaction",
        "proximity sequencing",
        "prox-seq",
        "sprox-seq",
        "spatial prox-seq",
        "spatial proximity sequencing",
        "protein complex",
        "protein complexes",
    ],

    # --- Biology / application ---
    "lymph_node": [
        "lymph node",
        "lymph nodes",
        "lymph-node",
        "lymphoid tissue",
        "secondary lymphoid",
        "secondary lymphoid organ",
        "slo",
        "paracortex",
        "subcapsular sinus",
        "medullary",
        "lymphatic",
    ],
    "germinal_center": [
        "germinal center",
        "germinal centre",
        "germinal-centre",
        "gc reaction",
        "germinal reaction",
        "light zone",
        "dark zone",
        "follicular",
        "follicle",
        "follicular dendritic",
        "fDC",
        "affinity maturation",
        "somatic hypermutation",
        "class switch",
        "isotype switching",
    ],
    "immune": [
        "immune",
        "immunology",
        "immunity",
        "t cell",
        "t-cell",
        "b cell",
        "b-cell",
        "tfh",
        "t follicular helper",
        "tfr",
        "t follicular regulatory",
        "macrophage",
        "dendritic cell",
        "antigen",
        "cytokine",
        "chemokine",
        "inflammation",
    ],
    "cancer": [
        "cancer",
        "tumor",
        "tumour",
        "oncology",
        "neoplasm",
        "malignant",
        "lymphoma",
        "metastasis",
    ],
    "drug": [
        "drug",
        "therapy",
        "therapeutic",
        "treatment",
        "inhibitor",
        "target",
        "small molecule",
        "antibody",
        "adc",
        "checkpoint",
        "immunotherapy",
    ],
    "bcell_antibody": [
        "antibody discovery",
        "antibody screening",
        "single-cell antibody",
        "single cell antibody",
        "antibody repertoire",
        "b cell receptor",
        "bcr",
        "vdj",
        "vdj sequencing",
        "paired heavy and light chain",
        "heavy and light chain",
        "neutralizing antibody",
    ],

    "tls": [
        "tertiary lymphoid",
        "tertiary lymphoid structure",
        "tls",
        "lymphoid aggregate",
    ],

    "ai_ml": [
        "deep learning",
        "machine learning",
        "artificial intelligence",
        "neural network",
        "convolutional neural network",
        "graph neural network",
        "transformer",
        "foundation model",
        "large language model",
        "generative model",
        "variational autoencoder",
        "diffusion model",
        "self-supervised",
        "self supervised",
        "contrastive learning",
        "transfer learning",
        "representation learning",
        "cell segmentation",
        "image segmentation",
        "image analysis",
        "computational pathology",
        "digital pathology",
        "spatial deconvolution",
        "cell type annotation",
        "cell type classification",
        "automated annotation",
        "clustering",
        "dimensionality reduction",
        "batch correction",
        "data integration",
        "multimodal integration",
        "imputation",
        "trajectory inference",
        "gene regulatory network",
        "cell-cell communication",
        "cell cell communication",
    ],
}

# ========================
# Focus: AI/ML in spatial omics, single-cell & imaging
# ========================
FOCUS_AI_KEYS = [
    "deep learning",
    "machine learning",
    "artificial intelligence",
    "neural network",
    "convolutional neural network",
    "graph neural network",
    "transformer",
    "foundation model",
    "large language model",
    "generative model",
    "variational autoencoder",
    "diffusion model",
    "self-supervised",
    "self supervised",
    "contrastive learning",
    "transfer learning",
    "representation learning",
    "cell segmentation",
    "image segmentation",
    "image analysis",
    "computational pathology",
    "digital pathology",
    "spatial deconvolution",
    "cell type annotation",
    "cell type classification",
    "automated annotation",
    "multimodal integration",
    "imputation",
    "trajectory inference",
    "gene regulatory network",
    "cell-cell communication",
    "cell cell communication",
]

# ========================
# Big-deal hints (broad advances)
# ========================
BIG_DEAL_HINTS = [
    "first-in-class",
    "breakthrough",
    "paradigm",
    "unexpected",
    "previously unknown",
    "landmark",
    "fundamental",
]

# ========================
# Trend lexicon (focused on LN / GC biology)
# ========================
TREND_LEXICON = {
    "Lymph node spatial organization": [
        "lymph node",
        "secondary lymphoid",
        "paracortex",
        "subcapsular sinus",
        "medullary",
        "lymphatic",
    ],
    "Germinal center dynamics": [
        "germinal center",
        "germinal centre",
        "dark zone",
        "light zone",
        "gc reaction",
        "affinity maturation",
        "somatic hypermutation",
    ],
    "TLS & immune aggregates": [
        "tertiary lymphoid",
        "tertiary lymphoid structure",
        "tls",
        "lymphoid aggregate",
    ],
    "B cell differentiation & fate": [
        "b cell fate",
        "plasma cell",
        "memory b cell",
        "class switch",
        "isotype switching",
    ],
    "T-B cell interaction & help": [
        "t follicular helper",
        "tfh",
        "t-b interaction",
        "cd40",
        "cd40l",
        "il-21",
    ],
    "Immune niche & microenvironment": [
        "immune niche",
        "microenvironment",
        "stromal cell",
        "fibroblastic reticular cell",
        "frc",
    ],
    "AI/ML in bio data analysis": [
        "deep learning",
        "machine learning",
        "neural network",
        "foundation model",
        "transformer",
        "cell segmentation",
        "computational pathology",
        "spatial deconvolution",
        "automated annotation",
    ],
}
